import Head from "next/head";
import Image from "next/image";
import JobDetail from "../components/jobs/JobDetail";
import Jobs from "../components/jobs/Jobs";
import Navbar from "../components/layout/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <section className={styles.main}>
        <Jobs />
      </section>
    </div>
  );
}
